#!/usr/bin/env node

if (process.env.NODE_ENV === 'production') {
  return
}

const childProcess = require('child_process')
const platform = require('os').platform()
const path = require('path')

const electronRebuildCmd = /^win/.test(platform) ? 'electron-rebuild.cmd' : 'electron-rebuild'
const cmd = path.join(process.cwd(), 'node_modules', '.bin', electronRebuildCmd)

childProcess.execFileSync(cmd, ['-s', '-t', 'prod,dev'], {
  env: process.env,
  stdio: 'inherit',
})
